---

deploy:
  hosts:
    localhost:
  vars:
    ce_deploy:
      own_repository: https://github.com/codeenigma/ce-deploy.git
      config_repository: https://github.com/codeenigma/ce-deploy-config-example.git
