---

# Utility servers, used for deploying code to other app servers.
utility:
  hosts:
    provision-utility: # This is the local example for ansible-provision.
    deploy-utility: # This is the local exampl for ansible-deploy.
    localhost: # Need this for now.
  vars:
    ansible_deploy:
      own_repository: https://github.com/codeenigma/ansible-deploy.git
      config_repository: git@jenkins.codeenigma.com:ce-ops/ansible-deploy-config.git
