---

# Utility servers, used for deploying code to other app servers.
utility:
  hosts:
    provision-utility: # This is the local example for ansible-provision.
    deploy-utility: # This is the local exampl for ansible-deploy.
  vars:
    ansible_deploy:
      config_repository: git@jenkins.codeenigma.com:ce-ops/ansible-deploy-config.git
